--- # EC2 TAGGING Modules exmaple
- hosts: localhost
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no
  tasks:
  - name: label an existing volume so we know what it is
    ec2_tag:
      region: eu-west-1
      resource: vol-099595c0731380268
      state: present
      tags:
        Name: data_volume
    register: voltags

      
      
      
  
